name: Deploy Application (Other Branch)
on:
  push:
    branches-ignore:
      - master
jobs:
  backend-other-branch:
    name: "Deploy other branch of backend"
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
      ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_SERVERLESS }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_SERVERLESS }}
      STAGE: dev
      AWS_DEFAULT_REGION: "us-east-1"
      NPM_GITHUB_PACKAGE_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGE_TOKEN }}
      APPLE_IAP_SHARED_SECRET: ${{ secrets.APPLE_IAP_SHARED_SECRET }}
      APPLE_STORE_SERVER_PRIVATE_KEY_ID: ${{ secrets.APPLE_STORE_SERVER_PRIVATE_KEY_ID }}
      APPLE_STORE_SERVER_PRIVATE_KEY: ${{ secrets.APPLE_STORE_SERVER_PRIVATE_KEY }}
      ANDROID_SERVICE_ACCOUNT_BASE64: ${{ secrets.ANDROID_SERVICE_ACCOUNT_BASE64 }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install
      - run: yarn cf:update-db && yarn cf:update-queue
        working-directory: ./server
      - name: Write android service account key from base64 secret
        working-directory: ./server
        run: |
          echo import certificate from secrets and regenerate the file
          echo $ANDROID_SERVICE_ACCOUNT_BASE64 | base64 -d > ./androidkey.json
      - run: ./node_modules/.bin/sls deploy --stage ${{ env.STAGE }} 
        working-directory: ./server
